name: Whatsapp
version: "1.1.0"
slug: whatsapp_addon
description: Whatsapp addon for send message from Home Assistant
url: "https://github.com/giuseppecastaldo/ha-addons/tree/main/whatsapp_addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config:rw
